title: Lerntagebuch Bibliotheks- und Archivinformatik
author: Anna
email: anna.staub@stud.fhgr.ch
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2024

# social links
github_username:  anna-staub # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
